sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - pip install 'lander>=0.1.0,<0.2'
  - pip install pyyaml    # for db2authors.py
script:
  # Pre-build authors.tex using the Travis CI Python
  - make authors.tex
  # Compile PDF using containerized lsst-texmf
  - docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh
    -c 'make'
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - lander --upload --pdf PSTN-039.pdf --lsstdoc PSTN-039.tex --env=travis --ltd-product
    pstn-039
env:
  global:
    -
      # LTD_AWS_ID
      secure: ocUC/3v2Gx8Juw7UfugFSoLgv/zBpJrC+rHTLxFvYi0Gn6pZ41MeDLvh1WMpFlW0FV4sq731iWfC05bEr0HtwRfX/RQAWHYSAzX0GL5yT/6hHfgEAKkBpNxxIhcHuC6dmJl7kPmW4h6U/kK+zWJO1Fmc1JNH7EdKkIVnRBGEUWQobB+6vMCH3wjtSFjICDPfJ3qf63UoK6yKwaaWh403EhKpnDcWodWghE4jS6wRdI9e+iM0Ktj91fEY8yzE65C+4Q6jmtBspPpx1zODz6mRK7ajIP062QBKiuAtKdOq0C0cIftB3Zc3YJ9RQHvxwNiNqnfArfiNPtdEZlH4X/B9h9MQZyUNHYhVo7yiGsIZi5v4cm2VDaQfppVBqp3Xaco9YYYm2hluzmbusU7FtbrSaALTeCKJoPFPDRpIBKZRNcm2Dy/d9oW8ev1QEwwN9R83ijk7Ko0zDLYCOhzPpekE/GPmQfbQC2/QTiNsb5mw7T/ImiRoZkNyzgp4DQk32ndYpkrduo1MGGY5yImTLn9nsW4FQegAjAuhXkxSrv0lOWBF6/QGmcH7iwN6oHBgY3KBvdruusmlMC43MG/BzBzVxooGGuC0U/4vlmjl8Sc/6m5STKsRTkjFVaW+iHUg2aJGEgNwaAJDYVXW5tJMdqVSEpmypxyYpxcQoAsc5PMYNDY=
    -
      # LTD_AWS_SECRET
      secure: srfz+iT7UAJHC/33ZnFV9dKZ6XaXWnnqXgwNjQPav/tqa2JdB/GWEdYwIx4EJ2GnwsFL3YvuWMovmfER0QHWnF/LTYkOVYELiCutm9uizzmq8p7asRL+YDS8uUpVqauJLla6eOdcFfwWFkiYBlkapvtNfhFcmAqonZQxNQrxkWxw5yrQBBLY+JEgmCWv8RE5yKH35pShWckrAuGwfqM/u5p0aJIaLD81tq/Bri3zHnGiyOeFsDvsR0kH4yeYWX43Opx20rpAYCH5YkGDf9hdOmEuUr3RL3EIUlKKk6yIUe4tTFF6tXnAXYax2iBaiZc9CQCP1actScjnhZ5TmUu36RwQvwFaIOujYnsyQkxaxCWRLBqRkEpmL5801JDgD+9At22UejOk9iauMq8cau6kTqjbnypDfhp96GEQjd9rBftaUUGX0xf4K97Vdl9Gcg8/6bnHEfd9oStobN4aCH+qig+ciCAuNZYqBzpfls+GFR8y+FPxv3gwzGalZxpt5OEg5LlLqniVI9EyLjzQ9RJcqjVXGJ///jBZdWjc5urELEalyAdgb3JMvsDr26Bq6ZXKUiD08EhZ/C19799Yi0z4qPXFtMH+g9AE6zIIBwC58rEa2Ou6eU0NYea5y1XRm/iLIEn5eqoku3BrHMTag1pemt+/zVIt2nRqi4bTwB0vPv4=
    -
      # LTD_KEEPER_USERNAME
      secure: T2MuVWYOaGD/CAsw3AUGyj0GeGPVo//pHtlVTgrNvPUD1wi1VUD1SpbRZJNtXqzGUp8FxLpG4Qpzoi182CHeBvOEs5ROgnFWT/b3lL7egq8xDp2WUWhSrEJQW2a317w09gDgKA2zjZ44q/7Fwzfz2Rfdkbw1mzYtTVNimxhCk1tkmlZHdrR7XShla3oZ5roG2nq7h7V2/tsRe+NAhu8wYV3x8lDmoOUnREF+c/S3fyiioEUxxqHt2gn7lPgPArDUbT2R/7xR/n/7veVefgvMZMxki9OU6J3Dr7ITHyCj3PXEDlaVoznV8CoCF96yeeWBWFAP4UDF0sKiaMVPUgXjMocUbcSp39qRLxgJ0HmDRMCB2s1/XKztGvU7efylrpL00CGzwNWq8d5Dr5VCSmBj+UUfszRnJh85dUXz/f92J81P52jBWkeiJvPyNY0Y3BBADIMPqE10ZFf89vXciL14b2rBaqqLhiPMQ8Vk6ALcGOeH8gXmiMxptn+qkjVrLz3T/TooXC3afSWCby3iWOh7VPr3lQsDBLrzXuGGb63t9E7DmlLge3k64/+xadIWGmoGe1UQOJP/5mQoUCwJynTsOaq2jKFuv3FlDfM7ao5P56l6af8otIA9K/VgHdtEbLnNaGGYGTnENVTc246GncUPCcwaUDzGZXAiEtI80BkDBVg=
    -
      # LTD_KEEPER_PASSWORD
      secure: XxIiipRrQcC3ZlhEeRxUsCxBr/2uV/fm20kUzmvDkAKLst3OYXQEGBhPdunPX3bJOjn8GXPV+Dm9Y1wrpvyZ0AlOnPEzjAuFSz+fLw9DxD7L4oQUO4GPLcCf5MrHkdxPorhkZsAAEQFJYo2bqnaN0+EMdXJDX19rmbPFiPN6Rz3dp8QjK/qAxB6twOLJ4/aaou15w1H9t4wIgDtOlE/ge1zYI2nRCaLxwCUHsGHc5c6XfCATKo49Do0S4A8U+ri+xPocOp+2MxC63u2iD5C7THUBZk/iOqRFHC305va+TnnfOGk7AgbY8b56wIaoedTqgHdcixb7SoEvfm3hvm3I0NEFlJatRt+4wOzmPaay/KjeiH276OP+1LKMl8q/pYhKolj2gdTvVPi3TD+elpeRhMPUCm/H4R+mK0WQiQCf+oy/t08gWoxjlld1owOlWTTJmGyZWo/+OmnEF1UKTFwG2M8DTe72Jr2pOpg9BhDE1Rzt0BPbYa++JAc3qVSIRSkgQGhls5ZqjcxAHB91xrvPQ8wtXZhBAi77guS7Yvr2zBMRs5hO4cp+KJCJ6pkvKK5sG2JopzbR+G8Rkr2hwMiyTXK7jOB911c8HTIJz0QagXmdpfFQLk21s2DC/AKnleRtnxKlE4kO29U3LSK8skln3woGZt1ajKJ7Zj2+NXuSA3I=
    -
      # LTD_KEEPER_URL
      secure: d+zjIQU+OszeSDq3Q66l5cbZ79aJrkpLkEUbdZ73OmwJgnVoH98fM/zm1+Eo3Z8EPSU6ZmsDrZNhW0fAUyfRyiC7FNfTo1Z9Ye7yCldGYgNVEvU+fsNI/Qh7xBy+XRQ3nRiL6F4OHvuy8m+juxue+ZnSbazlD4R4m94e78HM1dQPFEFV7Zk52FuaJ8ZgUMAv0Y8iP7tQ5vkRrrZhg6QK7s+auSC8bpJpntfGNPiSOO+OwUuNrXnuGVXillhLvagFLRysXrX0hvAR/ogJL2KNTFcezbQaDJE4uBV4u9lHM4Ec/knDBK1lcP0csgQfc1qMv/ubqhqoN9cZv9O4Gg8A3DrQolzJvl/n3k5yDciEgIU0sdZHxh0E7Xq7Ercbfo5Hihgnt148WHrhiY9EjwLcnKDMLReLYKndeKsB1PyaODrJimKvv8LDUrKLL4Rci7motJ1m6kRjnumrA+AVB5/dd+p9sHpszGAs5PoFqydwRnvF1paezdsKtH0kyER0++i5pagrOUo+ycimRE7xP8eXAkb2UPbAeQNBAC3oSJOBAYDzNnqdEK/Hfx0g6vrG3iOU1ecwJMOJFcuhLg19npr7xEsv3x2e792YTXI3jIF/wLiFurzaRU5RbOiADePFfbPMMRZGbOGJnh+ncFbTpyPJB4yiuKyFByYAdoMQO46nDeA=
